apiVersion: v1
kind: Service
metadata:
  labels:
    app: hocastencilsample
  name: hocastencilsampleservice
spec:
  type: LoadBalancer
  selector:
    app: hocastencilsample
  ports:
    - name: hocastencilsampleservice
      port: 8089
      targetPort: 80
